---
version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:

  - main: "./main.go"
    binary: oidc-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      # - arm
      # - 386
    ldflags:
      ## auto inject commit and version at build time
      - -X github.com/vdbulcke/oidc-server-demo/src/cmd.GitCommit={{ .ShortCommit }} 
      - -X github.com/vdbulcke/oidc-server-demo/src/cmd.Version=v{{ .Version }}   
      - -X github.com/vdbulcke/oidc-server-demo/src/cmd.Date={{ .CommitDate }} 
      - -X github.com/vdbulcke/oidc-server-demo/src/cmd.BuiltBy=goreleaser

archives:
  - 
    # replacements:
    #   ## Rewrite Archive name 
    #   darwin: Darwin
    #   linux: Linux
    #   windows: Windows
    #   386: i386
    #   amd64: x86_64
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ## use zip for windows release
    format_overrides:
      - goos: windows
        format: zip
    # files:
    # - LICENSE

## create MacOS universal binary
universal_binaries:
## set to true to ONLY generate a universal binary 
- replace: false

checksum:
  name_template: 'checksums.txt'



changelog:
  sort: asc
  filters:
    exclude:
      ## ignore commits from change log that starts with
      - '^docs:'
      - '^test:'
      - '^typo:'
      - '^ignore:'
  # Group commits messages by given regex and title.
  # Order value defines the order of the groups.
  # Proving no regex means all commits will be grouped under the default group.
  # Groups are disabled when using github-native, as it already groups things by itself.
  #
  # Default is no groups.
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999


dockers:
  - 
    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # GOARM of the built binaries/packages that should be used.
    goarm: ''

    ## Mutli platform 
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64

    image_templates:
    - "ghcr.io/vdbulcke/oidc-server:v{{ .Version }}"

  - 
    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: arm64

    # GOARM of the built binaries/packages that should be used.
    goarm: ''

    ## Mutli platform 
    use: buildx
    build_flag_templates:
    - --platform=linux/arm64/v8


    image_templates:
    - "ghcr.io/vdbulcke/oidc-server:v{{ .Version }}-arm64"

release:
  ## set github header and footer
  header: |
    ## Docker

    [https://github.com/vdbulcke/oidc-server/pkgs/container/oidc-server](https://github.com/vdbulcke/oidc-server/pkgs/container/oidc-server)

    
    ```bash
    docker pull ghcr.io/vdbulcke/oidc-server:v{{ .Version }}
    ```
    > NOTE: arm64 Docker images have tags ending in `-arm64`

    ### Run

    ```bash 
    docker run --rm  -v /path/to/your/config.yaml:/app/config.yaml:z -p 8080:5557 ghcr.io/vdbulcke/oidc-server:v{{ .Version }} --debug 
    ```

    NOTE: the `issuer_base_url` is required for docker.
    
#   # Footer template for the release body.
#   # Defaults to empty.
#   footer: |
#     ## Thanks!

#     Those were the changes on {{ .Tag }}!
